// src/services/contratosService.js

export class ContratosService {
    static lista = [
    { nombre: "AFFIRMATIVE ASYLUM OUT OF THE YEAR (AA FUERA DEL AÑO)", precio: 10500, conyuge: 2000, hijos: 500, downpayment: 4000 },
    { nombre: "AFFIRMATIVE ASYLUM FOLLOW-UP + EVIDENCE PACKAGE", precio: 7000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "ASYLUM INTERVIEW PREPARATION + EVIDENCE PACKAGE (Menos 30 días)", precio: 4000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "APPEARANCE AS ATTORNET (CREDIBLE FEAR INTERVIEW), proceedings in ICE", precio: 3500, conyuge: null, hijos: null, downpayment: null },
    { nombre: "FAMILY PETITION INTERVIEW", precio: 2500, conyuge: null, hijos: null, downpayment: null },
    { nombre: "DEFENSIVE ASYLUM", precio: 12500, conyuge: 2000, hijos: 500, downpayment: 5000 },
    { nombre: "AFFIRMATIVE ASYLUM", precio: 10500, conyuge: 2000, hijos: 500, downpayment: 4000 },
    { nombre: "CANCELLATION OF REMOVAL", precio: 10500, conyuge: null, hijos: null, downpayment: 3500 },
    { nombre: "INDIVIDUAL COURT ATTORNEY REPRESENTATION (REPRESENTATION + AMENDMENT/RELIEF)", precio: 8500, conyuge: null, hijos: null, downpayment: 8500 },
    { nombre: "APPEARANCE AS ATTORNEY WITH INTENT TO FILE A MOTION TO TERMINATED", precio: 5000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "REPRESENTATION OF DETAINEES", precio: 5000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "REPRESENTATION OF ATTORNEY (E61)", precio: 2500, conyuge: null, hijos: null, downpayment: null },
    { nombre: "LEGAL CALL", precio: 1000, conyuge: null, hijos: null, downpayment: 1000 },
    { nombre: "ALTERNATIVE TO DETENTION", precio: 3000, conyuge: null, hijos: null, downpayment: 3000 },
    { nombre: "BOND", precio: 4500, conyuge: null, hijos: null, downpayment: 4500 },
    { nombre: "ATTORNEY REPRESENTATION / BAIL REQUEST", precio: 7000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "APPEAL (NEW CUSTOMER)", precio: 7000, conyuge: null, hijos: null, downpayment: 6500 },
    { nombre: "APPEAL (ACTIVE CLIENT)", precio: 4500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "REOPEN (STAY OF REMOVAL)", precio: 6000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "REOPEN + I-589 (NON-ACTIVE CUSTOMER)", precio: 6000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "REOPEN + I-589 (ACTIVE CUSTOMER)", precio: 5000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "REQUEST FILE E-59", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "LEGAL FAMILY PETITION", precio: 8000, conyuge: 1500, hijos: 1500, downpayment: 2500 },
    { nombre: "IRREGULAR COMPLETE FAMILY PETITION", precio: 9000, conyuge: null, hijos: 1500, downpayment: 2500 },
    { nombre: "PAROLE IN PLACE (ARMY) (NEW CUSTOMER)", precio: 3000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "PAROLE IN PLACE (ARMY) (ACTIVE CLIENT)", precio: 2500, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "FAMILY PETITION FOR PIP (MILITARY)", precio: 7000, conyuge: 1500, hijos: 1500, downpayment: 2500 },
    { nombre: "IRREGULAR IMMEDIATE FAMILY PETITION (I - 130)", precio: 3000, conyuge: 1500, hijos: null, downpayment: 1500 },
    { nombre: "FAMILY PETITION (PREFERENCE CATEGORY I-130)", precio: 3000, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "FAMILY PETITION FOR ASYLUM OR REFUGEE (I-730)", precio: 3000, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "FAMILY PETITION STAGE 2 (CONSULAR PROCESS) NVC", precio: 4000, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "MINOR LAW (STAGE 1: ORDER OF DEPENDENCY)", precio: 5000, conyuge: null, hijos: null, downpayment: 3500 },
    { nombre: "MINOR LAW (STAGE 2: I-360 + I-765 PETITION FOR SPECIAL IMMIGRANT)", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "JUVENILE LAW (STAGE 3: I-485 ADJUSTMENT STATUS)", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "CUBAN ADJUSTMENT WITH NO CUT ADMISSION (I-485 STATUS ADJUSTMENT)", precio: 5000, conyuge: 1500, hijos: 1500, downpayment: 1500 },
    { nombre: "RESIDENCE / ADJUSTMENT OF STATUS", precio: 4500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "RESIDENCE (CARD RENEWAL OR LOSS)", precio: 2500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "RENEWAL OF RESIDENCY + WITHDRAWAL OF CONDITIONS (FOR. I-751)", precio: 3000, conyuge: null, hijos: null, downpayment: 3000 },
    { nombre: "STATUS ADJUSTEMENT + 245-I", precio: 5000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "CITIZENSHIP PROCESS (N-400)", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "CITIZENSHIP PROCESS (N-600)", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "REPLACEMENT OF CITIZENSHIP", precio: 2000, conyuge: null, hijos: null, downpayment: 2000 },
    { nombre: "APPEARANCE AS ATTORNEY, proceedings in USCIS (CRBA)", precio: 2500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "VISA U CERTIFICATION", precio: 2000, conyuge: null, hijos: null, downpayment: 2000 },
    { nombre: "VISA U", precio: 5500, conyuge: 1500, hijos: 1500, downpayment: 1500 },
    { nombre: "VISA T", precio: 5500, conyuge: 1500, hijos: 1500, downpayment: 1500 },
    { nombre: "VAWA (CITIZEN)", precio: 6000, conyuge: null, hijos: 1500, downpayment: 1500 },
    { nombre: "VAWA (RESIDENT)", precio: 8000, conyuge: null, hijos: 1500, downpayment: 1500 },
    { nombre: "VISA FIANCE", precio: 2000, conyuge: null, hijos: 1500, downpayment: 1500 },
    { nombre: "WAIVER (IRREGULAR PRESENCE) I-601A", precio: 4000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "WAIVER (FOR INADMISSIBILITY) I-601", precio: 4000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "WAIVER (FOR DEPORTATION) I-212", precio: 4000, conyuge: null, hijos: null, downpayment: 2500 },
    { nombre: "RENOVACIÓN DACA", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "TPS (NEW CUSTOMER)", precio: 2500, conyuge: 2000, hijos: null, downpayment: 1500 },
    { nombre: "TPS (ACTIVE CLIENT)", precio: 2000, conyuge: 2000, hijos: null, downpayment: 1500 },
    { nombre: "REQUEST FOR USCIS", precio: 2000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "ADVANCE PAROLE", precio: 1500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "ORGANIZED DEPORTATION", precio: 3000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "VOLUNTARY DEPARTURE", precio: 3500, conyuge: null, hijos: null, downpayment: null },
    { nombre: "STAY OF REMOVAL", precio: 3500, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "WORK PERMIT", precio: 1620, conyuge: null, hijos: null, downpayment: 1500 },
    { nombre: "WORK PERMIT RENEWAL", precio: 870, conyuge: null, hijos: null, downpayment: 750 },
    { nombre: "FINGERPRINTS", precio: 1878, conyuge: null, hijos: null, downpayment: null },
    { nombre: "FOIA OUTSIDE THE US", precio: 880, conyuge: null, hijos: null, downpayment: 880 },
    { nombre: "FOIA", precio: 780, conyuge: null, hijos: null, downpayment: 780 },
    { nombre: "DISMISSAL I589 USCIS", precio: 5000, conyuge: null, hijos: null, downpayment: null },
    { nombre: "ASYLUM APPOINTMENT REDHEDULING", precio: 2500, conyuge: null, hijos: null, downpayment: null },
    { nombre: "ADJUSTMENT OF REFUGEE STATUS", precio: 4500, conyuge: 2000, hijos: 1500, downpayment: 1500 },
    { nombre: "ICE ACCOMPANIMENT BY LAWYER", precio: 2500, conyuge: null, hijos: null, downpayment: null },
    ]
}

